use std::{
    fs,
    path::{Path, PathBuf},
};

use serde::{Deserialize, Serialize};

use crate::{error::AppError, mounts::models::MountRecord};

#[derive(Debug, Clone, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct FuseStartReport {
    pub mount_point: String,
    pub fuse_available: bool,
    pub message: String,
    pub gitignore_hint: Option<String>,
}

pub fn project_mount_point(project_root: &Path, mount_id: &str) -> PathBuf {
    project_root.join(".traceway").join("mounts").join(mount_id)
}

pub fn ensure_mount_point(path: &Path) -> Result<(), AppError> {
    fs::create_dir_all(path)?;
    Ok(())
}

pub fn gitignore_hint(project_root: &Path) -> Option<String> {
    let expected = ".traceway/mounts/";
    let gitignore = project_root.join(".gitignore");
    let content = fs::read_to_string(gitignore).unwrap_or_default();
    if content
        .lines()
        .map(str::trim)
        .any(|line| line == expected || line == ".traceway/" || line == ".traceway/mounts")
    {
        None
    } else {
        Some(format!(
            "Add `{expected}` to .gitignore before committing project files."
        ))
    }
}

pub fn start_readonly_mount(record: &MountRecord) -> Result<FuseStartReport, AppError> {
    let mount_point = PathBuf::from(&record.mount_point);
    ensure_mount_point(&mount_point)?;
    let project_root = mount_point
        .parent()
        .and_then(Path::parent)
        .and_then(Path::parent);
    let gitignore_hint = project_root.and_then(gitignore_hint);

    Err(AppError::BadRequest(format!(
        "FUSE mounting is not available in this build or macFUSE is not installed. \
         Virtual content can still be generated by the backend router, but the filesystem mount \
         at '{}' was not started. {}",
        record.mount_point,
        gitignore_hint.clone().unwrap_or_default()
    )))
}

pub fn stop_readonly_mount(_record: &MountRecord) -> FuseStartReport {
    FuseStartReport {
        mount_point: _record.mount_point.clone(),
        fuse_available: false,
        message: "No FUSE mount was running in this MVP build.".to_string(),
        gitignore_hint: None,
    }
}

pub fn readonly_write_error() -> AppError {
    AppError::BadRequest("Project context mounts are read-only".to_string())
}

#[cfg(test)]
mod tests {
    use std::{
        fs,
        time::{SystemTime, UNIX_EPOCH},
    };

    use super::*;

    #[test]
    fn gitignore_hint_is_absent_when_traceway_mounts_are_ignored() {
        let root = unique_temp_dir("gitignore");
        fs::create_dir_all(&root).expect("create temp root");
        fs::write(root.join(".gitignore"), ".traceway/mounts/\n").expect("write gitignore");

        assert!(gitignore_hint(&root).is_none());

        fs::remove_dir_all(root).ok();
    }

    #[test]
    fn project_mount_point_uses_traceway_mounts_directory() {
        let root = PathBuf::from("/tmp/project");

        assert_eq!(
            project_mount_point(&root, "mysql-main"),
            PathBuf::from("/tmp/project/.traceway/mounts/mysql-main")
        );
    }

    fn unique_temp_dir(prefix: &str) -> PathBuf {
        let stamp = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .expect("system clock before unix epoch")
            .as_nanos();
        std::env::temp_dir().join(format!(
            "csm-mount-{prefix}-{}-{stamp}",
            std::process::id()
        ))
    }
}
